apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: f1jcchkul-go 
  janus-idp.io/tekton: f1jcchkul-go
  backstage.io/kubernetes-id: f1jcchkul-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f1jcchkul-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml